apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: redisext
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis
  metrics:
  - type: External
    external:
      metricName: system.cpu.system
      metricSelector:
        matchLabels:
            kube_container_name: redis
      targetAverageValue: 15