apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: redisext
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: redis
  metrics:
  - type: External
    external:
      metricName: redis.net.commands
      metricSelector:
        matchLabels:
            kube_container_name: redis
      targetAverageValue: 15